# 基于PISL样条学习和HumanMAC扩散模型的人体动作预测配置文件

# 模型配置
model_config:
  # 基本参数
  n_joints: 22                    # 关节数量 (Human3.6M)
  input_dim: 66                   # 输入维度 (n_joints * 3)
  d_model: 512                    # 模型隐藏维度
  
  # PISL样条学习参数
  spline_degree: 3                # B样条度数
  n_control_points: 10            # 控制点数量
  physics_weight: 1.0             # 物理约束权重
  smoothness_weight: 0.1          # 平滑性权重
  
  # HumanMAC扩散模型参数
  n_encoder_layers: 6             # 编码器层数
  n_decoder_layers: 6             # 解码器层数
  n_heads: 8                      # 注意力头数
  d_ff: 2048                      # 前馈网络维度
  max_seq_len: 1000               # 最大序列长度
  dropout: 0.1                    # Dropout率
  n_timesteps: 1000               # 扩散时间步数
  beta_schedule: "cosine"         # 噪声调度 ("linear" 或 "cosine")
  
  # 融合模型参数
  fusion_weight: 0.5              # 融合权重

# 训练配置
training_config:
  # 基本训练参数
  batch_size: 16                  # 批大小
  learning_rate: 1.0e-4           # 学习率
  num_epochs: 100                 # 训练轮数
  warmup_epochs: 10               # 预热轮数
  weight_decay: 1.0e-5            # 权重衰减
  gradient_clip_norm: 1.0         # 梯度裁剪
  
  # 保存和评估
  save_interval: 10               # 保存间隔
  eval_interval: 5                # 评估间隔
  
  # 序列长度
  history_length: 25              # 历史序列长度
  future_length: 25               # 未来序列长度

# 数据配置
data_config:
  # 数据路径
  data_dir: "./data"              # 数据目录
  
  # 数据集划分
  train_subjects:                 # 训练主体
    - "S1"
    - "S5" 
    - "S6"
    - "S7"
    - "S8"
  val_subjects:                   # 验证主体
    - "S9"
    - "S11"
  test_subjects:                  # 测试主体
    - "S9"
    - "S11"
  
  # 数据预处理
  normalize_method: "standard"    # 标准化方法 ("standard", "minmax", "none")
  fps: 30                         # 帧率
  
  # 数据增强
  augmentation: true              # 是否使用数据增强
  augmentation_config:
    add_noise: true               # 添加噪声
    noise_std: 0.01               # 噪声标准差
    rotation: true                # 旋转增强
    rotation_angles: [-10, 10]    # 旋转角度范围
    mirror: true                  # 镜像翻转
    time_scaling: false           # 时间缩放
    scale_factors: [0.8, 1.2]     # 缩放因子

# 实验配置
experiment_config:
  # 实验信息
  experiment_name: "pisl_humanmac_fusion"  # 实验名称
  description: "PISL样条学习与HumanMAC扩散模型融合的人体动作预测"
  
  # 路径配置
  save_dir: "./checkpoints"       # 模型保存目录
  log_dir: "./logs"               # 日志目录
  results_dir: "./results"        # 结果保存目录
  
  # 设备配置
  device: "cuda"                  # 设备 ("cuda" 或 "cpu")
  num_workers: 4                  # 数据加载工作进程数
  pin_memory: true                # 是否固定内存
  
  # 日志配置
  use_tensorboard: true           # 使用TensorBoard
  use_wandb: false                # 使用Weights & Biases
  wandb_project: "human_motion_prediction"  # W&B项目名
  wandb_entity: null              # W&B实体名
  
  # 可视化配置
  save_visualizations: true       # 保存可视化结果
  visualization_interval: 20      # 可视化间隔
  max_vis_samples: 5              # 最大可视化样本数

# 评估配置
evaluation_config:
  # 评估指标
  metrics:
    - "mpjpe"                     # 平均关节位置误差
    - "p_mpjpe"                   # Procrustes对齐MPJPE
    - "velocity_error"            # 速度误差
    - "acceleration_error"        # 加速度误差
    - "bone_consistency"          # 骨骼一致性
    - "smoothness"                # 平滑度
  
  # 详细评估
  compute_detailed_metrics: true   # 计算详细指标
  save_predictions: true          # 保存预测结果
  
  # 可视化评估
  create_videos: true             # 创建对比视频
  video_fps: 30                   # 视频帧率
  max_video_length: 100           # 最大视频长度

# 推理配置
inference_config:
  # 模型路径
  model_path: "./checkpoints/best_model.pth"  # 模型权重路径
  
  # 推理参数
  batch_size: 1                   # 推理批大小
  use_pisl_only: false            # 仅使用PISL
  use_diffusion_only: false       # 仅使用扩散模型
  use_fusion: true                # 使用融合模型
  
  # 扩散采样参数
  sampling_method: "ddim"         # 采样方法 ("ddpm" 或 "ddim")
  n_sampling_steps: 50            # 采样步数
  eta: 0.0                        # DDIM参数
  
  # 输出配置
  save_results: true              # 保存结果
  output_format: "numpy"          # 输出格式 ("numpy", "json")
  create_visualization: true      # 创建可视化

# 优化配置
optimization_config:
  # 优化器
  optimizer: "adamw"              # 优化器类型
  beta1: 0.9                      # Adam beta1
  beta2: 0.999                    # Adam beta2
  eps: 1.0e-8                     # Adam epsilon
  
  # 学习率调度
  scheduler: "cosine"             # 调度器类型
  min_lr: 1.0e-6                  # 最小学习率
  
  # 正则化
  label_smoothing: 0.0            # 标签平滑
  mixup_alpha: 0.0                # Mixup参数

# 硬件配置
hardware_config:
  # GPU配置
  gpu_ids: [0]                    # GPU ID列表
  mixed_precision: true           # 混合精度训练
  
  # 内存优化
  gradient_accumulation_steps: 1  # 梯度累积步数
  max_memory_usage: 0.8           # 最大内存使用率
  
  # 分布式训练
  distributed: false              # 分布式训练
  world_size: 1                   # 世界大小
  rank: 0                         # 进程排名

# 调试配置
debug_config:
  # 调试模式
  debug_mode: false               # 调试模式
  fast_dev_run: false             # 快速开发运行
  overfit_batches: 0              # 过拟合批次数
  
  # 日志级别
  log_level: "INFO"               # 日志级别
  print_model_summary: true       # 打印模型摘要
  
  # 检查点
  resume_from_checkpoint: null    # 从检查点恢复
  save_top_k: 3                   # 保存最佳k个模型